import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Package, Loader2, QrCode, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/contexts/AuthContext";
import type { Json } from "@/integrations/supabase/types";

interface TipoTalla {
  id: string;
  nombre: string;
  valores: string[];
}

interface VariacionInput {
  tipoTallaId: string;
  talla: string;
  cantidad: number;
}

const Products = () => {
  const { toast } = useToast();
  const { canManageProducts } = useAuth();
  const queryClient = useQueryClient();
  
  const [formData, setFormData] = useState({
    imei: "",
    nombre: "",
    descripcion: "",
    imagen: "",
  });
  
  const [variaciones, setVariaciones] = useState<VariacionInput[]>([]);
  const [selectedTipoTalla, setSelectedTipoTalla] = useState<string>("");

  // Fetch tipo_tallas
  const { data: tipoTallas } = useQuery({
    queryKey: ['tipo_tallas'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('tipo_tallas')
        .select('*');
      if (error) throw error;
      return data.map(tt => ({
        ...tt,
        valores: Array.isArray(tt.valores) ? (tt.valores as Json[]).map(v => String(v)) : []
      })) as TipoTalla[];
    }
  });

  // Fetch productos with variaciones
  const { data: productos, isLoading: loadingProductos } = useQuery({
    queryKey: ['productos'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('productos')
        .select(`
          *,
          variaciones_producto (
            id,
            talla,
            stock_disponible,
            tipo_talla:tipo_tallas (nombre)
          )
        `)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data;
    }
  });

  // Create producto mutation
  const createProducto = useMutation({
    mutationFn: async () => {
      if (!formData.imei || !formData.nombre) {
        throw new Error("IMEI y nombre son requeridos");
      }
      if (variaciones.length === 0) {
        throw new Error("Debe agregar al menos una variación de talla");
      }

      // 1. Create producto
      const { data: producto, error: productoError } = await supabase
        .from('productos')
        .insert({
          imei: formData.imei,
          nombre: formData.nombre,
          descripcion: formData.descripcion || null,
          imagen_url: formData.imagen || null,
        })
        .select()
        .single();

      if (productoError) throw productoError;

      // 2. Create variaciones and productos_individuales
      for (const variacion of variaciones) {
        const { data: variacionData, error: variacionError } = await supabase
          .from('variaciones_producto')
          .insert({
            producto_id: producto.id,
            tipo_talla_id: variacion.tipoTallaId,
            talla: variacion.talla,
            stock_disponible: variacion.cantidad,
          })
          .select()
          .single();

        if (variacionError) throw variacionError;

        // 3. Create productos_individuales (QR auto-generated by trigger)
        const individuales = Array.from({ length: variacion.cantidad }, () => ({
          variacion_id: variacionData.id,
          estado: 'disponible' as const,
          qr_code: 'TEMP', // Will be replaced by database trigger
        }));

        const { error: individualesError } = await supabase
          .from('productos_individuales')
          .insert(individuales);

        if (individualesError) throw individualesError;
      }

      return producto;
    },
    onSuccess: (producto) => {
      toast({
        title: "Producto Creado",
        description: `${producto.nombre} con ${variaciones.reduce((acc, v) => acc + v.cantidad, 0)} unidades individuales`,
      });
      setFormData({ imei: "", nombre: "", descripcion: "", imagen: "" });
      setVariaciones([]);
      queryClient.invalidateQueries({ queryKey: ['productos'] });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    }
  });

  // Delete producto mutation
  const deleteProducto = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('productos')
        .delete()
        .eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      toast({ title: "Producto eliminado" });
      queryClient.invalidateQueries({ queryKey: ['productos'] });
    },
    onError: (error: Error) => {
      toast({
        title: "Error al eliminar",
        description: error.message,
        variant: "destructive",
      });
    }
  });

  const addVariacion = (talla: string) => {
    if (!selectedTipoTalla) return;
    
    const exists = variaciones.find(v => v.tipoTallaId === selectedTipoTalla && v.talla === talla);
    if (exists) {
      setVariaciones(variaciones.map(v => 
        v.tipoTallaId === selectedTipoTalla && v.talla === talla 
          ? { ...v, cantidad: v.cantidad + 1 }
          : v
      ));
    } else {
      setVariaciones([...variaciones, { tipoTallaId: selectedTipoTalla, talla, cantidad: 1 }]);
    }
  };

  const removeVariacion = (tipoTallaId: string, talla: string) => {
    setVariaciones(variaciones.filter(v => !(v.tipoTallaId === tipoTallaId && v.talla === talla)));
  };

  const updateCantidad = (tipoTallaId: string, talla: string, cantidad: number) => {
    if (cantidad < 1) return;
    setVariaciones(variaciones.map(v => 
      v.tipoTallaId === tipoTallaId && v.talla === talla ? { ...v, cantidad } : v
    ));
  };

  const selectedTipoTallaData = tipoTallas?.find(t => t.id === selectedTipoTalla);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    createProducto.mutate();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Gestión de Productos</h1>
        <p className="text-muted-foreground mt-1">
          Crear y administrar productos del catálogo
        </p>
      </div>

      {canManageProducts && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Plus className="h-5 w-5" />
              Crear Nuevo Producto
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="imei">IMEI / Código *</Label>
                  <Input
                    id="imei"
                    placeholder="Ej: VES-001"
                    value={formData.imei}
                    onChange={(e) => setFormData({ ...formData, imei: e.target.value })}
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="nombre">Nombre del Producto *</Label>
                  <Input
                    id="nombre"
                    placeholder="Ej: Vestido Elegante Azul"
                    value={formData.nombre}
                    onChange={(e) => setFormData({ ...formData, nombre: e.target.value })}
                    required
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="descripcion">Descripción</Label>
                <Textarea
                  id="descripcion"
                  placeholder="Descripción detallada del producto..."
                  value={formData.descripcion}
                  onChange={(e) => setFormData({ ...formData, descripcion: e.target.value })}
                  rows={2}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="imagen">URL de Imagen</Label>
                <Input
                  id="imagen"
                  type="url"
                  placeholder="https://ejemplo.com/imagen.jpg"
                  value={formData.imagen}
                  onChange={(e) => setFormData({ ...formData, imagen: e.target.value })}
                />
              </div>

              {/* Variaciones */}
              <div className="space-y-3 border-t pt-4">
                <Label>Variaciones de Talla *</Label>
                
                <div className="flex gap-2 items-end">
                  <div className="flex-1">
                    <Label className="text-xs text-muted-foreground">Tipo de Talla</Label>
                    <Select value={selectedTipoTalla} onValueChange={setSelectedTipoTalla}>
                      <SelectTrigger>
                        <SelectValue placeholder="Seleccionar tipo" />
                      </SelectTrigger>
                      <SelectContent>
                        {tipoTallas?.map(tipo => (
                          <SelectItem key={tipo.id} value={tipo.id}>{tipo.nombre}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {selectedTipoTallaData && (
                  <div className="flex flex-wrap gap-2">
                    {selectedTipoTallaData.valores.map(talla => (
                      <Button
                        key={talla}
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addVariacion(talla)}
                      >
                        + {talla}
                      </Button>
                    ))}
                  </div>
                )}

                {variaciones.length > 0 && (
                  <div className="space-y-2 mt-3">
                    <Label className="text-xs text-muted-foreground">Variaciones agregadas:</Label>
                    {variaciones.map((v) => {
                      const tipoNombre = tipoTallas?.find(t => t.id === v.tipoTallaId)?.nombre || '';
                      return (
                        <div key={`${v.tipoTallaId}-${v.talla}`} className="flex items-center gap-2 bg-muted/50 p-2 rounded">
                          <Badge variant="secondary">{tipoNombre}</Badge>
                          <span className="font-medium">{v.talla}</span>
                          <span className="text-muted-foreground">×</span>
                          <Input
                            type="number"
                            min={1}
                            value={v.cantidad}
                            onChange={(e) => updateCantidad(v.tipoTallaId, v.talla, parseInt(e.target.value) || 1)}
                            className="w-20 h-8"
                          />
                          <span className="text-sm text-muted-foreground">unidades</span>
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => removeVariacion(v.tipoTallaId, v.talla)}
                          >
                            <Trash2 className="h-4 w-4 text-destructive" />
                          </Button>
                        </div>
                      );
                    })}
                    <p className="text-sm text-muted-foreground">
                      Total: {variaciones.reduce((acc, v) => acc + v.cantidad, 0)} unidades individuales (con QR automático)
                    </p>
                  </div>
                )}
              </div>

              <Button 
                type="submit" 
                className="w-full md:w-auto"
                disabled={createProducto.isPending}
              >
                {createProducto.isPending ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Plus className="h-4 w-4 mr-2" />
                )}
                Crear Producto
              </Button>
            </form>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="h-5 w-5" />
            Productos Existentes
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loadingProductos ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : productos && productos.length > 0 ? (
            <div className="space-y-4">
              {productos.map((producto) => (
                <div key={producto.id} className="border rounded-lg p-4">
                  <div className="flex justify-between items-start">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{producto.imei}</Badge>
                        <h3 className="font-semibold">{producto.nombre}</h3>
                      </div>
                      {producto.descripcion && (
                        <p className="text-sm text-muted-foreground mt-1">{producto.descripcion}</p>
                      )}
                      <div className="flex flex-wrap gap-2 mt-2">
                        {producto.variaciones_producto?.map((v: any) => (
                          <Badge key={v.id} variant="secondary" className="flex items-center gap-1">
                            <QrCode className="h-3 w-3" />
                            {v.talla} ({v.stock_disponible})
                          </Badge>
                        ))}
                      </div>
                    </div>
                    {canManageProducts && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteProducto.mutate(producto.id)}
                        disabled={deleteProducto.isPending}
                      >
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No hay productos registrados aún
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default Products;
